runtime: python38
entrypoint: gunicorn --bind 0.0.0.0:8000 --workers 3 --threads 8 --timeout 120 wsgi:app
runtime_config:
    python_version: 3
manual_scaling:
  instances: 1
service: branded-car-verification

